[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/records"
  to = "/.netlify/functions/records"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/auth"
  status = 200
